---

- name: 7zip installer

  hosts: all

  tasks:

    - name: Download the 7zip installer

      win_get_url:

        url: https://www.7-zip.org/a/7z1701-x64.msi

        dest: C:\7z1701-x64.msi


    - name: Install MSI

      win_package:

        path: C:\7z1701-x64.msi
        
    - name: Clean up installer
      win_file:
       path: C:\7z1701-x64.msi
       state: absent
