---

- name: 7zip installer

  hosts: all

  tasks:

    - name: Download the 7zip installer

      win_get_url:

        url: https://7-zip.org/a/7z2201-x64.exe

        dest: C:\7z1701-x64.exe


    - name: Install 7zip

      script: ./files/install.ps1


        
    - name: Clean up installer
      win_file:
       path: C:\7z1701-x64.exe
       state: absent
