---
- name: create_txt_test
  hosts: all
  gather_facts: false
  tasks:
    - name: Copy script to remote host
      win_copy:
        src: files/create_file.ps1
        dest: C:\create_file.ps1
        
        
        - name: Run powershell script
        win_shell: C:\create_file.ps1
        register: res
        - debug: msg="{{ res }}"
