---
- hosts: all
  tasks:
  - name: Run a command under cmd
    win_command: netsh advfirewall show allprofiles state
    register: result
  - name: printig results
    debug:
      msg: "{{result}}"
   
