---
- name: 'Step 1: Role ensures that the socks tunnel is setup'
  hosts: all
  gather_facts: false
  roles:
    - role: ansible-role-event-socks-tunnel
      run_once: true
      delegate_to: localhost
      vars:
        acc_id: "{{ blueid_shortcode }}"
        transaction_id: "{{ tower_job_id }}"
 
- name: Test Playbook
  hosts: all
  tasks:
  - name: Run shell
    win_shell: |
      $filename = hostname
      $alldrive = Get-PSDrive -PSProvider FileSystem
      #$alldrive.Root
      #$Drives = "C:\","D:\","E:\","L:\"
      Get-ChildItem -Path $alldrive.Root -Recurse -Include *.exe -ErrorAction SilentlyContinue | Where {$_.Name -match 'openssl'} | Export-Csv -Path "C:\Windows\Temp\$filename-$(get-date -f dd-MM-yyyy)_openssl_report.csv"
      $fileObj = Get-Item -Path C:\Windows\Temp\$filename-$(get-date -f dd-MM-yyyy)_openssl_report.csv
      if ($fileObj.Length -gt 420) {
        Send-MailMessage -From 'sandriska.12@gmail.com' -To 'sandriska.12@gmail.com' -Subject "Opensll report $($filename)" -Body "Sending the Openssl report in csv" -Attachments "C:\Windows\Temp\$filename-$(get-date -f dd-MM-yyyy)_openssl_report.csv" -SmtpServer 'smtp.gmail.com'
      }
      else {
         Send-MailMessage -From 'sandriska.12@gmail.com' -To 'sandriska.12@gmail.com' -Subject "Opensll report $($filename)" -Body "Openssl not installed" -SmtpServer 'smtp.gmail.com'
      }
